/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Baundary;

import Controller.DempsterShefter;
import Controller.NaiveBayes;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class DiagnosisView extends javax.swing.JFrame {

    /**
     * Creates new form DiagnosisView
     */
    public DiagnosisView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        gejala9 = new javax.swing.JCheckBox();
        gejala10 = new javax.swing.JCheckBox();
        gejala11 = new javax.swing.JCheckBox();
        gejala12 = new javax.swing.JCheckBox();
        gejala13 = new javax.swing.JCheckBox();
        gejala14 = new javax.swing.JCheckBox();
        gejala15 = new javax.swing.JCheckBox();
        gejala16 = new javax.swing.JCheckBox();
        gejala17 = new javax.swing.JCheckBox();
        gejala18 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        gejala1 = new javax.swing.JCheckBox();
        gejala3 = new javax.swing.JCheckBox();
        gejala2 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        gejala4 = new javax.swing.JCheckBox();
        gejala6 = new javax.swing.JCheckBox();
        gejala5 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        gejala7 = new javax.swing.JCheckBox();
        gejala8 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(218, 183, 163));

        jPanel5.setBackground(new java.awt.Color(218, 184, 122));

        gejala9.setText("Sebagian Kulit Kering");

        gejala10.setText("Komedo Hitam Diwajah");

        gejala11.setText("Berjerawat");
        gejala11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gejala11ActionPerformed(evt);
            }
        });

        gejala12.setText("Kulit Wajah Tampak Mengkilat");
        gejala12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gejala12ActionPerformed(evt);
            }
        });

        gejala13.setText("Pori Pori Besar");

        gejala14.setText("Tidak Mudah Timbul Kerutan");

        gejala15.setText("Tekstur Kulit Wajah Tipis");

        gejala16.setText("Mudah Mengalami Alergi (Gatal / Ruam)");

        gejala17.setText("Mudah Iritasi dan Terluka");
        gejala17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gejala17ActionPerformed(evt);
            }
        });

        gejala18.setText("Kulit Mudah Kemerahan");
        gejala18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gejala18ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(33, 87, 74));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Diagnois");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(211, 155, 117));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("DIAGNOSIS KULIT WAJAH");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Pilih gejalah yang dialami");

        jPanel1.setBackground(new java.awt.Color(98, 130, 114));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Naive bayes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTable1.setBackground(new java.awt.Color(218, 183, 163));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Kode Jenis", "Jenis Kulit", "bobot", "penjelasan"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 68, Short.MAX_VALUE))
        );

        gejala1.setText("Kulit Tidak Berminyak");
        gejala1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gejala1ActionPerformed(evt);
            }
        });

        gejala3.setText("Tidak Mudah Berjerawat");

        gejala2.setText("Kulit Terlihat Halus dan Sehat");
        gejala2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gejala2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(98, 130, 114));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dempster Shafer", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTable2.setBackground(new java.awt.Color(218, 183, 163));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Kode Jenis", "Jenis Kulit", "Bobot", "Penjelasan"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        gejala4.setText("Pori Pori Kecil");

        gejala6.setText("Mudah Timbul Kerutan");

        gejala5.setText("Kulit Terlihat Kering dan Kasar");

        jButton2.setBackground(new java.awt.Color(33, 87, 74));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Masukan Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        gejala7.setText("Kusam");
        gejala7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gejala7ActionPerformed(evt);
            }
        });

        gejala8.setText("Kulit Berminyak di Area T-Zone (Dahi, Hidung, Dagu)");

        jLabel3.setText("*Klik Masukan Data jika memiliki data kondisi kulit yang dialami");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Solusi :\n1. Kulit Normal = Perawatan untuk kulit wajah normal cukup mudah, gunakan  sabun cuci wajah dengan bahan kimia yang lembut dan tidak menggosok wajah dengan kasar\n2. Kulit Kering = untuk merawat kulit wajah kering gunakan sabun cuci wajah yang dapat melembabkan kulit wajah seperti emolien, hindari produk  skincare yang mengandung alkohol dan pewangi, sert rajin menggunakan pelembab, hindari mandi terlalu lama dan mencuci muka dengan air hangat.\n3. Kulit Berminyak = Perawatan kulit wajah berminyak disarankan rajin untuk mencuci wajah 2 kali sehari. gunakan pelembab yang oil free dan berbahan dasar air. hindari makan makanan tidak sehat seperti gorengan, makanan cepat saji, serta makanan dengan kadar gula yang tinggi. Bahan bahan yang dianjurkan untuk kulit wajah berminyak anatara lain gliserin, benzoil proksida, asam salisat, asam slikolat, madu, lidah buaya, serta tomat.\n4. Kulit Kombinasi = untuk merawat kulit wajah kombinasi gunakan produk khusus untuk kulit wajah kombinasi serta mampu mengurangi minyak wajah diarea T-zone, gunakan tabir surya, serta melakukan pola hidup sehat dengan mengkonsumsi makanan bernutrisis, perbanyak minum air putih, dan tidak merokok. untuk kulit wajah kombinasi diharapkan untuk tidak sembarangan menggunkanan produk perawatan wajah dan sebaiknya melakukan konsultasi ke dokter spesialis kulit.\n5. Kulit Sensitif = perawatan kulit wajah sensitif diharapkan mengetahui pemicu dari terjadinya iritasi dan alergi diwajah, gunakan sabun cuci muka yang berbahan lembut dan tidak menggosok wajah dengan lembut, hindari produk skincare yang mengandung, alkohol, asam, dan pewangi karena dapat menyebabkan wajah menjadi iritasi. produk yang cocok untuk kulit wajah ini adalah produk yang mengandung lida buaya, chamomile, teh hijau, polifenol, dan gandum.");
        jScrollPane4.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(291, 291, 291)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(279, 279, 279))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addComponent(gejala7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(156, 156, 156))
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(gejala10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addComponent(gejala13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(40, 40, 40)))
                                                        .addGap(78, 78, 78))
                                                    .addComponent(gejala16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(10, 10, 10)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addComponent(gejala11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(196, 196, 196))
                                                    .addComponent(gejala8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addComponent(gejala14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(116, 116, 116))
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addComponent(gejala17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(128, 128, 128)))
                                                .addGap(14, 14, 14))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(gejala1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addComponent(gejala4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(36, 36, 36)))
                                                .addGap(101, 101, 101)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addComponent(gejala2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(4, 4, 4))
                                                    .addComponent(gejala5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(122, 122, 122)))
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(gejala3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                                        .addComponent(gejala6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(10, 10, 10)))
                                                .addGap(36, 36, 36))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addComponent(gejala9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(42, 42, 42))
                                                    .addComponent(gejala12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addComponent(gejala15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(24, 24, 24))
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addComponent(gejala18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(30, 30, 30)))
                                                .addGap(10, 10, 10)))))))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(263, 263, 263))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gejala1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gejala2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gejala3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gejala4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gejala5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gejala6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gejala7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gejala8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gejala9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gejala10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gejala11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gejala12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gejala13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gejala14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gejala15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gejala16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gejala17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gejala18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(13, 13, 13))
        );

        jScrollPane5.setViewportView(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane5)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gejala1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gejala1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gejala1ActionPerformed

    private void gejala12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gejala12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gejala12ActionPerformed

    private void gejala17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gejala17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gejala17ActionPerformed

    private void gejala18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gejala18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gejala18ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList<Double> gejala = new ArrayList<>();
        ArrayList<String> temp = new ArrayList<>();
        
        if(gejala1.isSelected()){
            gejala.add(1.0);
            temp.add("1");
        }else{
            gejala.add(0.0);
        }
        
        if(gejala2.isSelected()){
            gejala.add(1.0);
            temp.add("1");
        }else{
            gejala.add(0.0);
        }
        
        if(gejala3.isSelected()){
            gejala.add(1.0);
            temp.add("1");
        }else{
            gejala.add(0.0);
        }
        
        if(gejala4.isSelected()){
            gejala.add(1.0);
            temp.add("1");
        }else{
            gejala.add(0.0);
        }
        
        if(gejala5.isSelected()){
            gejala.add(1.0);
            temp.add("1");
        }else{
            gejala.add(0.0);
        }
        
        if(gejala6.isSelected()){
            gejala.add(1.0);
            temp.add("1");
        }else{
            gejala.add(0.0);
        }
        
        if(gejala7.isSelected()){
            gejala.add(1.0);
            temp.add("1");
        }else{
            gejala.add(0.0);
        }
        
        if(gejala8.isSelected()){
            gejala.add(1.0);
            temp.add("1");
        }else{
            gejala.add(0.0);
        }
        
        if(gejala9.isSelected()){
            gejala.add(1.0);
            temp.add("1");
        }else{
            gejala.add(0.0);
        }
        
        if(gejala10.isSelected()){
            gejala.add(1.0);
            temp.add("1");
        }else{
            gejala.add(0.0);
        }
        
        if(gejala11.isSelected()){
            gejala.add(1.0);
            temp.add("1");
        }else{
            gejala.add(0.0);
        }
        
        if(gejala12.isSelected()){
            gejala.add(1.0);
            temp.add("1");
        }else{
            gejala.add(0.0);
        }
        
        if(gejala13.isSelected()){
            gejala.add(1.0);
            temp.add("1");
        }else{
            gejala.add(0.0);
        }
        
        if(gejala14.isSelected()){
            gejala.add(1.0);
            temp.add("1");
        }else{
            gejala.add(0.0);
        }
        
        if(gejala15.isSelected()){
            gejala.add(1.0);
            temp.add("1");
        }else{
            gejala.add(0.0);
        }
        
        if(gejala16.isSelected()){
            gejala.add(1.0);
            temp.add("1");
        }else{
            gejala.add(0.0);
        }
        
        if(gejala17.isSelected()){
            gejala.add(1.0);
            temp.add("1");
        }else{
            gejala.add(0.0);
        }
        
        if(gejala18.isSelected()){
            gejala.add(1.0);
            temp.add("1");
        }else{
            gejala.add(0.0);
        }
        
        if (temp.isEmpty()){
           JOptionPane.showMessageDialog(null, "pilih gejalah");  
        }else if (temp.size() == 1) {
            JOptionPane.showMessageDialog(null, "pilih gejalah minimal 2"); 
        }
        else {
            JOptionPane.showMessageDialog(null, "berhasil diagnosis");  
        
        ArrayList<ArrayList> data_uji = new ArrayList<>();
        data_uji.add(gejala);
        NaiveBayes nb = new NaiveBayes();        
        nb.do_naive_bayes(data_uji);
        
        ArrayList<String> hasil = nb.get_hasil();
        ArrayList<String> penyakit = nb.get_penyakit();
        ArrayList<String> penjelasan = nb.get_penjelasan();
        ArrayList<Double> bobot = nb.get_bobot();
        
        DefaultTableModel data_header = new DefaultTableModel(new String[]{
            "Kode Jenis",
            "Jenis Kulit",
            "Bobot",
            "Penjelasan"
        }, 0);
        jTable1.setModel(data_header); // set table header
        for (int i = 0; i < hasil.size(); i++) {
            data_header.addRow(new Object[]{
                hasil.get(i),
                penyakit.get(i),
                bobot.get(i),
                penjelasan.get(i)
            });
            
        }
        
        DempsterShefter nb2 = new DempsterShefter();   
        nb2.do_dempster(data_uji);  
        
        ArrayList<String> hasilDs = nb2.get_hasil();
        ArrayList<String> penyakitDs = nb2.get_penyakit();
        ArrayList<String> penjelasanDs = nb2.get_penjelasan();
        ArrayList<Double> bobotDs = nb2.get_bobot();
        
        DefaultTableModel data_headerDs = new DefaultTableModel(new String[]{
            "Kode Jenis",
            "Jenis Kulit",
            "Bobot",
            "Penjelasan"
        }, 0);
        jTable2.setModel(data_headerDs); // set table header
        for (int i = 0; i < hasilDs.size(); i++) {
            data_headerDs.addRow(new Object[]{
                hasilDs.get(i),
                penyakitDs.get(i),
                bobotDs.get(i),
                penjelasanDs.get(i)
            });
        }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void gejala7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gejala7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gejala7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //new NewJFrame().show();
        new NewJFrame().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void gejala2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gejala2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gejala2ActionPerformed

    private void gejala11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gejala11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gejala11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagnosisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagnosisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagnosisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagnosisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiagnosisView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox gejala1;
    private javax.swing.JCheckBox gejala10;
    private javax.swing.JCheckBox gejala11;
    private javax.swing.JCheckBox gejala12;
    private javax.swing.JCheckBox gejala13;
    private javax.swing.JCheckBox gejala14;
    private javax.swing.JCheckBox gejala15;
    private javax.swing.JCheckBox gejala16;
    private javax.swing.JCheckBox gejala17;
    private javax.swing.JCheckBox gejala18;
    private javax.swing.JCheckBox gejala2;
    private javax.swing.JCheckBox gejala3;
    private javax.swing.JCheckBox gejala4;
    private javax.swing.JCheckBox gejala5;
    private javax.swing.JCheckBox gejala6;
    private javax.swing.JCheckBox gejala7;
    private javax.swing.JCheckBox gejala8;
    private javax.swing.JCheckBox gejala9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables

    private boolean gejala(double d) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
